/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type CustomerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "customer";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  items?: Array<{
    product?: ProductReference;
    quantity?: number;
    priceAtPurchase?: number;
    _key: string;
  }>;
  total?: number;
  status?: "paid" | "shipped" | "delivered" | "cancelled";
  customer?: CustomerReference;
  userId?: string;
  email?: string;
  address?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  stripePaymentId?: string;
  createdAt?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  price?: number;
  category?: CategoryReference;
  material?:
    | "stainless steel"
    | "sterling silver"
    | "gold-plated"
    | "gold-filled"
    | "surgical steel"
    | "crystal"
    | "pearl"
    | "titanium"
    | "enamel";
  color?:
    | "gold"
    | "silver"
    | "rose gold"
    | "white"
    | "black"
    | "multi"
    | "pink"
    | "green";
  dimensions?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  stock?: number;
  featured?: boolean;
  assemblyRequired?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email?: string;
  name?: string;
  userId?: string;
  stripeCustomerId?: string;
  createdAt?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductReference
  | CustomerReference
  | Order
  | CategoryReference
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Customer
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: app/api/admin/insights/route.ts
// Variable: ADMIN_METRICS_QUERY
// Query: {  "currentRevenue": math::sum(*[_type == "order" && status in ["paid", "shipped", "delivered"] && dateTime(createdAt) > dateTime(now()) - 60*60*24*30].total),  "previousRevenue": math::sum(*[_type == "order" && status in ["paid", "shipped", "delivered"] && dateTime(createdAt) > dateTime(now()) - 60*60*24*60 && dateTime(createdAt) <= dateTime(now()) - 60*60*24*30].total),  "orderCount": count(*[_type == "order" && dateTime(createdAt) > dateTime(now()) - 60*60*24*30]),  "unfulfilledCount": count(*[_type == "order" && status in ["paid", "pending"]]),  "lowStockCount": count(*[_type == "product" && stock > 0 && stock <= 5]),  "outOfStockCount": count(*[_type == "product" && stock == 0]),  "totalProducts": count(*[_type == "product"]),  "topProducts": *[_type == "order" && dateTime(createdAt) > dateTime(now()) - 60*60*24*30].items[].product->name}
export type ADMIN_METRICS_QUERY_RESULT = {
  currentRevenue: number;
  previousRevenue: number;
  orderCount: number;
  unfulfilledCount: number;
  lowStockCount: number;
  outOfStockCount: number;
  totalProducts: number;
  topProducts: Array<string | null>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '{\n  "currentRevenue": math::sum(*[_type == "order" && status in ["paid", "shipped", "delivered"] && dateTime(createdAt) > dateTime(now()) - 60*60*24*30].total),\n  "previousRevenue": math::sum(*[_type == "order" && status in ["paid", "shipped", "delivered"] && dateTime(createdAt) > dateTime(now()) - 60*60*24*60 && dateTime(createdAt) <= dateTime(now()) - 60*60*24*30].total),\n  "orderCount": count(*[_type == "order" && dateTime(createdAt) > dateTime(now()) - 60*60*24*30]),\n  "unfulfilledCount": count(*[_type == "order" && status in ["paid", "pending"]]),\n  "lowStockCount": count(*[_type == "product" && stock > 0 && stock <= 5]),\n  "outOfStockCount": count(*[_type == "product" && stock == 0]),\n  "totalProducts": count(*[_type == "product"]),\n  "topProducts": *[_type == "order" && dateTime(createdAt) > dateTime(now()) - 60*60*24*30].items[].product->name\n}': ADMIN_METRICS_QUERY_RESULT;
  }
}
