import { defineField, defineType } from "sanity";

export const seoFieldsType = defineType({
  name: "seoFields",
  title: "SEO",
  type: "object",
  fields: [
    defineField({
      name: "metaTitle",
      title: "Meta Title",
      type: "string",
      description: "Page title shown in Google results. Max 60 characters.",
      validation: (rule) => rule.max(60).warning("Keep under 60 characters for best display in Google"),
    }),
    defineField({
      name: "metaDescription",
      title: "Meta Description",
      type: "text",
      rows: 3,
      description: "Google search result snippet. Max 160 characters.",
      validation: (rule) => rule.max(160).warning("Keep under 160 characters"),
    }),
    defineField({
      name: "ogTitle",
      title: "Social Share Title",
      type: "string",
      description: "Title when shared on WhatsApp, Facebook, Instagram. Max 60 chars.",
      validation: (rule) => rule.max(60),
    }),
    defineField({
      name: "ogDescription",
      title: "Social Share Description",
      type: "text",
      rows: 3,
      description: "Description for social sharing. Max 160 characters.",
      validation: (rule) => rule.max(160),
    }),
    defineField({
      name: "ogImage",
      title: "Social Share Image",
      type: "image",
      description: "Custom image for social sharing. Falls back to product/category image if not set.",
      options: { hotspot: true },
    }),
    defineField({
      name: "focusKeyword",
      title: "Focus Keyword",
      type: "string",
      description: "Primary keyword this page targets, e.g. 'gold pendant necklace Nairobi'",
    }),
    defineField({
      name: "secondaryKeywords",
      title: "Secondary Keywords",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      description: "Additional keywords: variations, materials, location, search intent",
    }),
    defineField({
      name: "canonicalUrl",
      title: "Canonical URL",
      type: "url",
      description: "Override canonical URL (leave blank to use the default page URL)",
    }),
    defineField({
      name: "noIndex",
      title: "Hide from Google",
      type: "boolean",
      initialValue: false,
      description: "Enable to exclude this page from Google search results (for drafts/test products)",
    }),
    defineField({
      name: "seoScore",
      title: "SEO Score (0–100)",
      type: "number",
      description: "AI-calculated SEO quality score. Auto-updated during generation.",
      readOnly: true,
    }),
    defineField({
      name: "lastSeoGeneration",
      title: "Last AI Generation",
      type: "datetime",
      description: "When AI last generated or updated this SEO content.",
      readOnly: true,
    }),
    defineField({
      name: "aiGenerated",
      title: "AI Generated",
      type: "boolean",
      initialValue: false,
      description: "Whether current SEO content was AI-generated.",
      readOnly: true,
    }),
  ],
});
